// <auto-generated />
using System;
using DontWasteFood.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DontWasteFood.Infrastructure.Migrations.DontWasteFoodDb
{
    [DbContext(typeof(DontWasteFoodDbContext))]
    [Migration("20241224161413_UpdateCity")]
    partial class UpdateCity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("DontWasteFood")
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DontWasteFood.Domain.Models.Canteen", b =>
                {
                    b.Property<Guid>("CanteenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CanteenLocation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HotMealsOffer")
                        .HasColumnType("bit");

                    b.HasKey("CanteenId");

                    b.ToTable("Canteens", "DontWasteFood");

                    b.HasData(
                        new
                        {
                            CanteenId = new Guid("4be48778-d81a-4eb5-bd1c-553f546a5966"),
                            CanteenLocation = "LA",
                            City = "Breda",
                            HotMealsOffer = true
                        },
                        new
                        {
                            CanteenId = new Guid("01086a90-ff33-4d5b-9b49-9cbbb6291efa"),
                            CanteenLocation = "DB",
                            City = "Den Bosch",
                            HotMealsOffer = true
                        });
                });

            modelBuilder.Entity("DontWasteFood.Domain.Models.CanteenWorker", b =>
                {
                    b.Property<Guid>("CanteenWorkerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CanteenId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EmployeeNumber")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<string>("IdentityUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CanteenWorkerId");

                    b.HasIndex("CanteenId");

                    b.HasIndex("EmployeeNumber")
                        .IsUnique();

                    b.ToTable("CanteenWorkers", "DontWasteFood");

                    b.HasData(
                        new
                        {
                            CanteenWorkerId = new Guid("4fdd4c4d-9cf0-4bfc-b9e4-df0329b7d77f"),
                            CanteenId = new Guid("4be48778-d81a-4eb5-bd1c-553f546a5966"),
                            EmployeeNumber = "1234567",
                            IdentityUserId = "4fdd4c4d-9cf0-4bfc-b9e4-df0329b7d77f",
                            Name = "John Doe"
                        },
                        new
                        {
                            CanteenWorkerId = new Guid("5f1e9cbc-9748-4e28-b7cc-b6d52ace34c7"),
                            CanteenId = new Guid("4be48778-d81a-4eb5-bd1c-553f546a5966"),
                            EmployeeNumber = "7654321",
                            Name = "Jan Jansen"
                        });
                });

            modelBuilder.Entity("DontWasteFood.Domain.Models.Package", b =>
                {
                    b.Property<Guid>("PackageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CanteenId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateOfPickUp")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Is18Plus")
                        .HasColumnType("bit");

                    b.Property<int>("MealType")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("StudentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("TimeOfPickUp")
                        .HasColumnType("datetime2");

                    b.HasKey("PackageId");

                    b.HasIndex("CanteenId");

                    b.HasIndex("StudentId");

                    b.ToTable("Packages", "DontWasteFood");

                    b.HasData(
                        new
                        {
                            PackageId = new Guid("a5305b5a-ec00-4626-925f-901f9b61bbf8"),
                            CanteenId = new Guid("4be48778-d81a-4eb5-bd1c-553f546a5966"),
                            DateOfPickUp = new DateTime(2024, 12, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Is18Plus = false,
                            MealType = 3,
                            Name = "Gevulde Koek met Fristi",
                            Price = 5.00m,
                            StudentId = new Guid("a96fda13-9eee-4a49-94b7-ddf4c84ec61e"),
                            TimeOfPickUp = new DateTime(2024, 12, 30, 16, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PackageId = new Guid("09051bc9-81fb-438d-9ffa-e0dab29213d0"),
                            CanteenId = new Guid("4be48778-d81a-4eb5-bd1c-553f546a5966"),
                            DateOfPickUp = new DateTime(2024, 12, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Is18Plus = true,
                            MealType = 2,
                            Name = "Amstel & Stroopwafel",
                            Price = 10.00m,
                            TimeOfPickUp = new DateTime(2024, 12, 13, 13, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PackageId = new Guid("8afc3f7f-0452-4db5-a0a3-6de0802419c1"),
                            CanteenId = new Guid("01086a90-ff33-4d5b-9b49-9cbbb6291efa"),
                            DateOfPickUp = new DateTime(2024, 12, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Is18Plus = false,
                            MealType = 0,
                            Name = "Broodje Gezond",
                            Price = 3.00m,
                            TimeOfPickUp = new DateTime(2024, 12, 14, 11, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PackageId = new Guid("20ee797e-8930-41d9-841e-acf3659640e1"),
                            CanteenId = new Guid("01086a90-ff33-4d5b-9b49-9cbbb6291efa"),
                            DateOfPickUp = new DateTime(2024, 12, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Is18Plus = false,
                            MealType = 0,
                            Name = "Panini Salami",
                            Price = 4.00m,
                            TimeOfPickUp = new DateTime(2024, 12, 20, 15, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("DontWasteFood.Domain.Models.Product", b =>
                {
                    b.Property<Guid>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsAlcoholic")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductId");

                    b.ToTable("Products", "DontWasteFood");

                    b.HasData(
                        new
                        {
                            ProductId = new Guid("88288629-2bfe-46a2-973e-175ff977fb99"),
                            IsAlcoholic = true,
                            Name = "Amstel",
                            PhotoUrl = "/images/amstel.jpg"
                        },
                        new
                        {
                            ProductId = new Guid("f3054f1f-f875-4e12-b891-7314711b0627"),
                            IsAlcoholic = false,
                            Name = "Broodje gezond",
                            PhotoUrl = "/images/broodje-gezond.jpg"
                        },
                        new
                        {
                            ProductId = new Guid("af827f12-12ee-475b-95d4-f2bb164993b5"),
                            IsAlcoholic = true,
                            Name = "Cola",
                            PhotoUrl = "/images/cola.jpg"
                        },
                        new
                        {
                            ProductId = new Guid("4d6fbfb7-f701-4a3a-96f5-2328d5ad3e9b"),
                            IsAlcoholic = false,
                            Name = "Fanta",
                            PhotoUrl = "/images/fanta.png"
                        },
                        new
                        {
                            ProductId = new Guid("2b24029b-ca23-41e0-946c-c65751b83ba5"),
                            IsAlcoholic = false,
                            Name = "Fristi",
                            PhotoUrl = "/images/fristi.png"
                        },
                        new
                        {
                            ProductId = new Guid("7dec6dc3-029a-41f3-89da-d535b213afd5"),
                            IsAlcoholic = false,
                            Name = "Gevulde Koek",
                            PhotoUrl = "/images/gevulde-koek.jpg"
                        },
                        new
                        {
                            ProductId = new Guid("fdbe441a-2d9b-44ef-8d95-d087785d7c02"),
                            IsAlcoholic = false,
                            Name = "Panini Salami",
                            PhotoUrl = "/images/panini-salami.jpg"
                        },
                        new
                        {
                            ProductId = new Guid("d86c27f0-daa1-4546-9a98-3df8bdab4229"),
                            IsAlcoholic = false,
                            Name = "Saucijzenbroodje",
                            PhotoUrl = "/images/saucijzenbroodje.png"
                        },
                        new
                        {
                            ProductId = new Guid("1a3c84e8-ef8f-4070-b1e9-d8da5c51f4de"),
                            IsAlcoholic = false,
                            Name = "Spa Blauw",
                            PhotoUrl = "/images/spa-blauw.jpg"
                        },
                        new
                        {
                            ProductId = new Guid("6af0b603-68a1-429d-b614-8e50f3aa2231"),
                            IsAlcoholic = false,
                            Name = "Stroopwafel",
                            PhotoUrl = "/images/stroopwafel.jpg"
                        });
                });

            modelBuilder.Entity("DontWasteFood.Domain.Models.Student", b =>
                {
                    b.Property<Guid>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("IdentityUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudentNumber")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.HasKey("StudentId");

                    b.HasIndex("EmailAddress")
                        .IsUnique();

                    b.HasIndex("StudentNumber")
                        .IsUnique();

                    b.ToTable("Students", "DontWasteFood");

                    b.HasData(
                        new
                        {
                            StudentId = new Guid("a96fda13-9eee-4a49-94b7-ddf4c84ec61e"),
                            City = "Breda",
                            DateOfBirth = new DateTime(2004, 8, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "el.stam@student.avans.nl",
                            IdentityUserId = "a96fda13-9eee-4a49-94b7-ddf4c84ec61e",
                            Name = "Esmée Stam",
                            StudentNumber = "2196911"
                        },
                        new
                        {
                            StudentId = new Guid("10a8c01b-7df8-42ca-bc43-7473dd6d4df4"),
                            City = "Den_Bosch",
                            DateOfBirth = new DateTime(2008, 3, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "j.doe@student.avans.nl",
                            Name = "Jane Doe",
                            StudentNumber = "2176034"
                        });
                });

            modelBuilder.Entity("PackageProduct", b =>
                {
                    b.Property<Guid>("PackagesPackageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductsProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PackageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PackagesPackageId", "ProductsProductId");

                    b.HasIndex("PackageId");

                    b.HasIndex("ProductId");

                    b.HasIndex("ProductsProductId");

                    b.ToTable("PackageProduct", "DontWasteFood");

                    b.HasData(
                        new
                        {
                            PackagesPackageId = new Guid("a5305b5a-ec00-4626-925f-901f9b61bbf8"),
                            ProductsProductId = new Guid("7dec6dc3-029a-41f3-89da-d535b213afd5")
                        },
                        new
                        {
                            PackagesPackageId = new Guid("a5305b5a-ec00-4626-925f-901f9b61bbf8"),
                            ProductsProductId = new Guid("2b24029b-ca23-41e0-946c-c65751b83ba5")
                        },
                        new
                        {
                            PackagesPackageId = new Guid("09051bc9-81fb-438d-9ffa-e0dab29213d0"),
                            ProductsProductId = new Guid("88288629-2bfe-46a2-973e-175ff977fb99")
                        },
                        new
                        {
                            PackagesPackageId = new Guid("09051bc9-81fb-438d-9ffa-e0dab29213d0"),
                            ProductsProductId = new Guid("6af0b603-68a1-429d-b614-8e50f3aa2231")
                        },
                        new
                        {
                            PackagesPackageId = new Guid("8afc3f7f-0452-4db5-a0a3-6de0802419c1"),
                            ProductsProductId = new Guid("f3054f1f-f875-4e12-b891-7314711b0627")
                        },
                        new
                        {
                            PackagesPackageId = new Guid("20ee797e-8930-41d9-841e-acf3659640e1"),
                            ProductsProductId = new Guid("fdbe441a-2d9b-44ef-8d95-d087785d7c02")
                        });
                });

            modelBuilder.Entity("DontWasteFood.Domain.Models.CanteenWorker", b =>
                {
                    b.HasOne("DontWasteFood.Domain.Models.Canteen", "Canteen")
                        .WithMany("CanteenWorkers")
                        .HasForeignKey("CanteenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Canteen");
                });

            modelBuilder.Entity("DontWasteFood.Domain.Models.Package", b =>
                {
                    b.HasOne("DontWasteFood.Domain.Models.Canteen", "Canteen")
                        .WithMany()
                        .HasForeignKey("CanteenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DontWasteFood.Domain.Models.Student", "ReservedBy")
                        .WithMany("Packages")
                        .HasForeignKey("StudentId");

                    b.Navigation("Canteen");

                    b.Navigation("ReservedBy");
                });

            modelBuilder.Entity("PackageProduct", b =>
                {
                    b.HasOne("DontWasteFood.Domain.Models.Package", null)
                        .WithMany()
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DontWasteFood.Domain.Models.Package", null)
                        .WithMany()
                        .HasForeignKey("PackagesPackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DontWasteFood.Domain.Models.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DontWasteFood.Domain.Models.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductsProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DontWasteFood.Domain.Models.Canteen", b =>
                {
                    b.Navigation("CanteenWorkers");
                });

            modelBuilder.Entity("DontWasteFood.Domain.Models.Student", b =>
                {
                    b.Navigation("Packages");
                });
#pragma warning restore 612, 618
        }
    }
}
