// <auto-generated />
using System;
using DontWasteFood.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DontWasteFood.Infrastructure.Migrations.DontWasteFoodDb
{
    [DbContext(typeof(DontWasteFoodDbContext))]
    [Migration("20241224161035_UpdateStringToEnum")]
    partial class UpdateStringToEnum
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("DontWasteFood")
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DontWasteFood.Domain.Models.Canteen", b =>
                {
                    b.Property<Guid>("CanteenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CanteenLocation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HotMealsOffer")
                        .HasColumnType("bit");

                    b.HasKey("CanteenId");

                    b.ToTable("Canteens", "DontWasteFood");

                    b.HasData(
                        new
                        {
                            CanteenId = new Guid("80b47e9e-7398-411b-bb44-ae0052aeec36"),
                            CanteenLocation = "LA",
                            City = "Breda",
                            HotMealsOffer = true
                        },
                        new
                        {
                            CanteenId = new Guid("2f3b01e4-b715-4d5a-90fc-e9217f23b2d0"),
                            CanteenLocation = "DB",
                            City = "Den_Bosch",
                            HotMealsOffer = true
                        });
                });

            modelBuilder.Entity("DontWasteFood.Domain.Models.CanteenWorker", b =>
                {
                    b.Property<Guid>("CanteenWorkerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CanteenId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EmployeeNumber")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<string>("IdentityUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CanteenWorkerId");

                    b.HasIndex("CanteenId");

                    b.HasIndex("EmployeeNumber")
                        .IsUnique();

                    b.ToTable("CanteenWorkers", "DontWasteFood");

                    b.HasData(
                        new
                        {
                            CanteenWorkerId = new Guid("4fdd4c4d-9cf0-4bfc-b9e4-df0329b7d77f"),
                            CanteenId = new Guid("80b47e9e-7398-411b-bb44-ae0052aeec36"),
                            EmployeeNumber = "1234567",
                            IdentityUserId = "4fdd4c4d-9cf0-4bfc-b9e4-df0329b7d77f",
                            Name = "John Doe"
                        },
                        new
                        {
                            CanteenWorkerId = new Guid("92e85afc-396b-42df-a73f-56eb66532cc8"),
                            CanteenId = new Guid("80b47e9e-7398-411b-bb44-ae0052aeec36"),
                            EmployeeNumber = "7654321",
                            Name = "Jan Jansen"
                        });
                });

            modelBuilder.Entity("DontWasteFood.Domain.Models.Package", b =>
                {
                    b.Property<Guid>("PackageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CanteenId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateOfPickUp")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Is18Plus")
                        .HasColumnType("bit");

                    b.Property<int>("MealType")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("StudentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("TimeOfPickUp")
                        .HasColumnType("datetime2");

                    b.HasKey("PackageId");

                    b.HasIndex("CanteenId");

                    b.HasIndex("StudentId");

                    b.ToTable("Packages", "DontWasteFood");

                    b.HasData(
                        new
                        {
                            PackageId = new Guid("66c691cc-0286-4dc8-90cc-87817fa4839e"),
                            CanteenId = new Guid("80b47e9e-7398-411b-bb44-ae0052aeec36"),
                            DateOfPickUp = new DateTime(2024, 12, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Is18Plus = false,
                            MealType = 3,
                            Name = "Gevulde Koek met Fristi",
                            Price = 5.00m,
                            StudentId = new Guid("a96fda13-9eee-4a49-94b7-ddf4c84ec61e"),
                            TimeOfPickUp = new DateTime(2024, 12, 30, 16, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PackageId = new Guid("9e9d4fff-7dab-4cc2-bcf8-66ddc059d117"),
                            CanteenId = new Guid("80b47e9e-7398-411b-bb44-ae0052aeec36"),
                            DateOfPickUp = new DateTime(2024, 12, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Is18Plus = true,
                            MealType = 2,
                            Name = "Amstel & Stroopwafel",
                            Price = 10.00m,
                            TimeOfPickUp = new DateTime(2024, 12, 13, 13, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PackageId = new Guid("9c177e27-13fb-4b58-96d7-6a3c8f4f1052"),
                            CanteenId = new Guid("2f3b01e4-b715-4d5a-90fc-e9217f23b2d0"),
                            DateOfPickUp = new DateTime(2024, 12, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Is18Plus = false,
                            MealType = 0,
                            Name = "Broodje Gezond",
                            Price = 3.00m,
                            TimeOfPickUp = new DateTime(2024, 12, 14, 11, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PackageId = new Guid("6dae2b06-8627-46b2-81dd-5b27ed416a43"),
                            CanteenId = new Guid("2f3b01e4-b715-4d5a-90fc-e9217f23b2d0"),
                            DateOfPickUp = new DateTime(2024, 12, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Is18Plus = false,
                            MealType = 0,
                            Name = "Panini Salami",
                            Price = 4.00m,
                            TimeOfPickUp = new DateTime(2024, 12, 20, 15, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("DontWasteFood.Domain.Models.Product", b =>
                {
                    b.Property<Guid>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsAlcoholic")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductId");

                    b.ToTable("Products", "DontWasteFood");

                    b.HasData(
                        new
                        {
                            ProductId = new Guid("56885c02-efb8-4b19-85ea-a772b779e8bd"),
                            IsAlcoholic = true,
                            Name = "Amstel",
                            PhotoUrl = "/images/amstel.jpg"
                        },
                        new
                        {
                            ProductId = new Guid("df80ea80-7b4a-4bad-a5e8-719344d0496c"),
                            IsAlcoholic = false,
                            Name = "Broodje gezond",
                            PhotoUrl = "/images/broodje-gezond.jpg"
                        },
                        new
                        {
                            ProductId = new Guid("09c3891f-207e-498e-b3d8-2358e814d301"),
                            IsAlcoholic = true,
                            Name = "Cola",
                            PhotoUrl = "/images/cola.jpg"
                        },
                        new
                        {
                            ProductId = new Guid("d2a1b26e-dcb6-414d-9f7f-f892c6c03748"),
                            IsAlcoholic = false,
                            Name = "Fanta",
                            PhotoUrl = "/images/fanta.png"
                        },
                        new
                        {
                            ProductId = new Guid("9c611891-a285-4760-a969-280b1c0d33d8"),
                            IsAlcoholic = false,
                            Name = "Fristi",
                            PhotoUrl = "/images/fristi.png"
                        },
                        new
                        {
                            ProductId = new Guid("aa775ff2-e551-420e-840f-b432f1f37e91"),
                            IsAlcoholic = false,
                            Name = "Gevulde Koek",
                            PhotoUrl = "/images/gevulde-koek.jpg"
                        },
                        new
                        {
                            ProductId = new Guid("529e6978-5c79-43a9-b721-d3f4e6bc5565"),
                            IsAlcoholic = false,
                            Name = "Panini Salami",
                            PhotoUrl = "/images/panini-salami.jpg"
                        },
                        new
                        {
                            ProductId = new Guid("3f8863ee-49c0-45e2-b5e9-c4c94ed52eb8"),
                            IsAlcoholic = false,
                            Name = "Saucijzenbroodje",
                            PhotoUrl = "/images/saucijzenbroodje.png"
                        },
                        new
                        {
                            ProductId = new Guid("a04f585b-c189-4917-9ddf-a622580b4291"),
                            IsAlcoholic = false,
                            Name = "Spa Blauw",
                            PhotoUrl = "/images/spa-blauw.jpg"
                        },
                        new
                        {
                            ProductId = new Guid("ad867539-1fd1-403e-91e7-7ae26539a8c9"),
                            IsAlcoholic = false,
                            Name = "Stroopwafel",
                            PhotoUrl = "/images/stroopwafel.jpg"
                        });
                });

            modelBuilder.Entity("DontWasteFood.Domain.Models.Student", b =>
                {
                    b.Property<Guid>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("IdentityUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudentNumber")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.HasKey("StudentId");

                    b.HasIndex("EmailAddress")
                        .IsUnique();

                    b.HasIndex("StudentNumber")
                        .IsUnique();

                    b.ToTable("Students", "DontWasteFood");

                    b.HasData(
                        new
                        {
                            StudentId = new Guid("a96fda13-9eee-4a49-94b7-ddf4c84ec61e"),
                            City = "Breda",
                            DateOfBirth = new DateTime(2004, 8, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "el.stam@student.avans.nl",
                            IdentityUserId = "a96fda13-9eee-4a49-94b7-ddf4c84ec61e",
                            Name = "Esmée Stam",
                            StudentNumber = "2196911"
                        },
                        new
                        {
                            StudentId = new Guid("a3c26886-31c7-4468-b6a2-4eca734eaa4d"),
                            City = "Den_Bosch",
                            DateOfBirth = new DateTime(2008, 3, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "j.doe@student.avans.nl",
                            Name = "Jane Doe",
                            StudentNumber = "2176034"
                        });
                });

            modelBuilder.Entity("PackageProduct", b =>
                {
                    b.Property<Guid>("PackagesPackageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductsProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PackageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PackagesPackageId", "ProductsProductId");

                    b.HasIndex("PackageId");

                    b.HasIndex("ProductId");

                    b.HasIndex("ProductsProductId");

                    b.ToTable("PackageProduct", "DontWasteFood");

                    b.HasData(
                        new
                        {
                            PackagesPackageId = new Guid("66c691cc-0286-4dc8-90cc-87817fa4839e"),
                            ProductsProductId = new Guid("aa775ff2-e551-420e-840f-b432f1f37e91")
                        },
                        new
                        {
                            PackagesPackageId = new Guid("66c691cc-0286-4dc8-90cc-87817fa4839e"),
                            ProductsProductId = new Guid("9c611891-a285-4760-a969-280b1c0d33d8")
                        },
                        new
                        {
                            PackagesPackageId = new Guid("9e9d4fff-7dab-4cc2-bcf8-66ddc059d117"),
                            ProductsProductId = new Guid("56885c02-efb8-4b19-85ea-a772b779e8bd")
                        },
                        new
                        {
                            PackagesPackageId = new Guid("9e9d4fff-7dab-4cc2-bcf8-66ddc059d117"),
                            ProductsProductId = new Guid("ad867539-1fd1-403e-91e7-7ae26539a8c9")
                        },
                        new
                        {
                            PackagesPackageId = new Guid("9c177e27-13fb-4b58-96d7-6a3c8f4f1052"),
                            ProductsProductId = new Guid("df80ea80-7b4a-4bad-a5e8-719344d0496c")
                        },
                        new
                        {
                            PackagesPackageId = new Guid("6dae2b06-8627-46b2-81dd-5b27ed416a43"),
                            ProductsProductId = new Guid("529e6978-5c79-43a9-b721-d3f4e6bc5565")
                        });
                });

            modelBuilder.Entity("DontWasteFood.Domain.Models.CanteenWorker", b =>
                {
                    b.HasOne("DontWasteFood.Domain.Models.Canteen", "Canteen")
                        .WithMany("CanteenWorkers")
                        .HasForeignKey("CanteenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Canteen");
                });

            modelBuilder.Entity("DontWasteFood.Domain.Models.Package", b =>
                {
                    b.HasOne("DontWasteFood.Domain.Models.Canteen", "Canteen")
                        .WithMany()
                        .HasForeignKey("CanteenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DontWasteFood.Domain.Models.Student", "ReservedBy")
                        .WithMany("Packages")
                        .HasForeignKey("StudentId");

                    b.Navigation("Canteen");

                    b.Navigation("ReservedBy");
                });

            modelBuilder.Entity("PackageProduct", b =>
                {
                    b.HasOne("DontWasteFood.Domain.Models.Package", null)
                        .WithMany()
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DontWasteFood.Domain.Models.Package", null)
                        .WithMany()
                        .HasForeignKey("PackagesPackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DontWasteFood.Domain.Models.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DontWasteFood.Domain.Models.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductsProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DontWasteFood.Domain.Models.Canteen", b =>
                {
                    b.Navigation("CanteenWorkers");
                });

            modelBuilder.Entity("DontWasteFood.Domain.Models.Student", b =>
                {
                    b.Navigation("Packages");
                });
#pragma warning restore 612, 618
        }
    }
}
