// <auto-generated />
using System;
using DontWasteFood.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DontWasteFood.Infrastructure.Migrations.DontWasteFoodDb
{
    [DbContext(typeof(DontWasteFoodDbContext))]
    [Migration("20250119184102_MoreSeedData")]
    partial class MoreSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("DontWasteFood")
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DontWasteFood.Domain.Models.Canteen", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CanteenLocation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("City")
                        .HasColumnType("int");

                    b.Property<bool>("HotMealsOffer")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Canteens", "DontWasteFood");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ff009029-24b5-44f5-8026-3761bbb6271c"),
                            CanteenLocation = "LA",
                            City = 0,
                            HotMealsOffer = true
                        },
                        new
                        {
                            Id = new Guid("ac2693c5-3aa3-4e77-95be-f624162f805a"),
                            CanteenLocation = "DB",
                            City = 1,
                            HotMealsOffer = true
                        },
                        new
                        {
                            Id = new Guid("da3941aa-8ef8-4364-b210-304ac5a547d6"),
                            CanteenLocation = "TI",
                            City = 2,
                            HotMealsOffer = false
                        });
                });

            modelBuilder.Entity("DontWasteFood.Domain.Models.CanteenWorker", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CanteenId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EmployeeNumber")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<string>("IdentityUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CanteenId");

                    b.HasIndex("EmployeeNumber")
                        .IsUnique();

                    b.ToTable("CanteenWorkers", "DontWasteFood");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1964dc4c-d543-496b-b536-000a3c334313"),
                            CanteenId = new Guid("ff009029-24b5-44f5-8026-3761bbb6271c"),
                            EmployeeNumber = "1234567",
                            IdentityUserId = "4fdd4c4d-9cf0-4bfc-b9e4-df0329b7d77f",
                            Name = "John Doe"
                        },
                        new
                        {
                            Id = new Guid("24340028-ad25-4538-b17c-bb0f9a2cf514"),
                            CanteenId = new Guid("ff009029-24b5-44f5-8026-3761bbb6271c"),
                            EmployeeNumber = "7654321",
                            IdentityUserId = "1dbd6d2b-4efb-4b56-93bc-90799c9beea5",
                            Name = "Jan Jansen"
                        },
                        new
                        {
                            Id = new Guid("edb77448-9a6a-474b-9e02-259985e5506d"),
                            CanteenId = new Guid("da3941aa-8ef8-4364-b210-304ac5a547d6"),
                            EmployeeNumber = "1234577",
                            IdentityUserId = "b1c79773-6d4c-4605-9603-1cf695f0cda3",
                            Name = "Tim Timmermans"
                        },
                        new
                        {
                            Id = new Guid("1e01341f-2546-4429-b4d7-e361f35baefd"),
                            CanteenId = new Guid("ff009029-24b5-44f5-8026-3761bbb6271c"),
                            EmployeeNumber = "7654322",
                            IdentityUserId = "c49a1c5f-b9ad-49e9-8cb7-7fcb54b3b39a",
                            Name = "Johan Jansen"
                        });
                });

            modelBuilder.Entity("DontWasteFood.Domain.Models.Package", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CanteenId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateOfPickUp")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Is18Plus")
                        .HasColumnType("bit");

                    b.Property<int>("MealType")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("StudentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("TimeOfPickUp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CanteenId");

                    b.HasIndex("StudentId");

                    b.ToTable("Packages", "DontWasteFood");

                    b.HasData(
                        new
                        {
                            Id = new Guid("18f10e8e-95c0-40bd-81a6-79e98b01cc8f"),
                            CanteenId = new Guid("ff009029-24b5-44f5-8026-3761bbb6271c"),
                            DateOfPickUp = new DateTime(2025, 1, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Is18Plus = false,
                            MealType = 3,
                            Name = "Gevulde Koek met Fristi",
                            Price = 5.00m,
                            StudentId = new Guid("ec8115e0-37aa-4b3b-a1e5-e343a2a82aad"),
                            TimeOfPickUp = new DateTime(2025, 1, 30, 16, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("f22e219d-cdeb-4292-b09c-a03228b6fb27"),
                            CanteenId = new Guid("ff009029-24b5-44f5-8026-3761bbb6271c"),
                            DateOfPickUp = new DateTime(2025, 1, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Is18Plus = true,
                            MealType = 2,
                            Name = "Amstel & Stroopwafel",
                            Price = 10.00m,
                            TimeOfPickUp = new DateTime(2025, 1, 13, 13, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("46c3bc0c-1725-4d4b-8671-18fade721fac"),
                            CanteenId = new Guid("ac2693c5-3aa3-4e77-95be-f624162f805a"),
                            DateOfPickUp = new DateTime(2025, 1, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Is18Plus = false,
                            MealType = 0,
                            Name = "Broodje Gezond",
                            Price = 3.00m,
                            TimeOfPickUp = new DateTime(2025, 1, 30, 11, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("68255d0d-fc3d-4e08-9b65-1b6d66a462fc"),
                            CanteenId = new Guid("ac2693c5-3aa3-4e77-95be-f624162f805a"),
                            DateOfPickUp = new DateTime(2025, 1, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Is18Plus = false,
                            MealType = 0,
                            Name = "Panini Salami",
                            Price = 4.00m,
                            TimeOfPickUp = new DateTime(2025, 1, 30, 15, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("30bb508b-4b34-4176-9577-5ba9aeb94a6e"),
                            CanteenId = new Guid("da3941aa-8ef8-4364-b210-304ac5a547d6"),
                            DateOfPickUp = new DateTime(2025, 1, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Is18Plus = false,
                            MealType = 2,
                            Name = "Fanta & Saucijzenbroodje",
                            Price = 4.50m,
                            TimeOfPickUp = new DateTime(2025, 1, 31, 14, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("2444f203-d6e2-4ebe-a8cd-7ad0467a7164"),
                            CanteenId = new Guid("da3941aa-8ef8-4364-b210-304ac5a547d6"),
                            DateOfPickUp = new DateTime(2025, 1, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Is18Plus = false,
                            MealType = 3,
                            Name = "Spa Blauw & Panini Salami",
                            Price = 5.50m,
                            TimeOfPickUp = new DateTime(2025, 1, 31, 16, 30, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("DontWasteFood.Domain.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsAlcoholic")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products", "DontWasteFood");

                    b.HasData(
                        new
                        {
                            Id = new Guid("db7b1a0e-6920-4bd2-b517-dc411635f85e"),
                            IsAlcoholic = true,
                            Name = "Amstel",
                            PhotoUrl = "/images/amstel.jpg"
                        },
                        new
                        {
                            Id = new Guid("afbd7019-aba7-4d6f-adc5-3bc30960d161"),
                            IsAlcoholic = false,
                            Name = "Broodje gezond",
                            PhotoUrl = "/images/broodje-gezond.jpg"
                        },
                        new
                        {
                            Id = new Guid("bf69778b-9ed3-47f6-a432-8b989a10d42f"),
                            IsAlcoholic = false,
                            Name = "Cola",
                            PhotoUrl = "/images/cola.jpg"
                        },
                        new
                        {
                            Id = new Guid("3ae01902-607f-42d2-8748-7adbbc8b1b39"),
                            IsAlcoholic = false,
                            Name = "Fanta",
                            PhotoUrl = "/images/fanta.png"
                        },
                        new
                        {
                            Id = new Guid("44a61765-faa6-4112-9f27-31470b00e70c"),
                            IsAlcoholic = false,
                            Name = "Fristi",
                            PhotoUrl = "/images/fristi.png"
                        },
                        new
                        {
                            Id = new Guid("73209267-a1ed-45a3-8ea2-a97074f38232"),
                            IsAlcoholic = false,
                            Name = "Gevulde Koek",
                            PhotoUrl = "/images/gevulde-koek.jpg"
                        },
                        new
                        {
                            Id = new Guid("157f4ced-fbed-403a-9efa-4e4a9b93257c"),
                            IsAlcoholic = false,
                            Name = "Panini Salami",
                            PhotoUrl = "/images/panini-salami.jpg"
                        },
                        new
                        {
                            Id = new Guid("4c4c47ed-dce2-4b80-b912-698f57f85f54"),
                            IsAlcoholic = false,
                            Name = "Saucijzenbroodje",
                            PhotoUrl = "/images/saucijzenbroodje.png"
                        },
                        new
                        {
                            Id = new Guid("a0e1ffc4-39b9-4f3c-a242-a44172172229"),
                            IsAlcoholic = false,
                            Name = "Spa Blauw",
                            PhotoUrl = "/images/spa-blauw.jpg"
                        },
                        new
                        {
                            Id = new Guid("5d1c9a4e-7968-4f94-a81c-ecca866c73a1"),
                            IsAlcoholic = false,
                            Name = "Stroopwafel",
                            PhotoUrl = "/images/stroopwafel.jpg"
                        });
                });

            modelBuilder.Entity("DontWasteFood.Domain.Models.Student", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("City")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("IdentityUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudentNumber")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.HasKey("Id");

                    b.HasIndex("EmailAddress")
                        .IsUnique();

                    b.HasIndex("StudentNumber")
                        .IsUnique();

                    b.ToTable("Students", "DontWasteFood");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ec8115e0-37aa-4b3b-a1e5-e343a2a82aad"),
                            City = 0,
                            DateOfBirth = new DateTime(2004, 8, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "el.stam@student.avans.nl",
                            IdentityUserId = "a96fda13-9eee-4a49-94b7-ddf4c84ec61e",
                            Name = "Esmée Stam",
                            StudentNumber = "2196911"
                        },
                        new
                        {
                            Id = new Guid("5fc90d6b-aa0a-4e9f-a4a9-691ebab27ff3"),
                            City = 1,
                            DateOfBirth = new DateTime(2008, 3, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "j.doe@student.avans.nl",
                            IdentityUserId = "bbfe56c9-88c2-4a60-9479-18b16d8c4c9d",
                            Name = "Jane Doe",
                            StudentNumber = "2176034"
                        },
                        new
                        {
                            Id = new Guid("942848fe-5958-41bc-8104-8813b9852ac8"),
                            City = 2,
                            DateOfBirth = new DateTime(2005, 4, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "n.jones@student.avans.nl",
                            IdentityUserId = "ea05a0b1-ea38-4c51-bde9-13c6fbb4b61b",
                            Name = "Norah Jones",
                            StudentNumber = "2176035"
                        },
                        new
                        {
                            Id = new Guid("d061b645-3245-4d38-a71b-1df5c0fbf8a5"),
                            City = 0,
                            DateOfBirth = new DateTime(2006, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "e.smith@student.avans.nl",
                            IdentityUserId = "c16e4b0b-d7b3-4845-a788-52411e76b5de",
                            Name = "Evie Smith",
                            StudentNumber = "2176036"
                        });
                });

            modelBuilder.Entity("PackageProduct", b =>
                {
                    b.Property<Guid>("PackagesId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductsId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PackagesId", "ProductsId");

                    b.HasIndex("ProductsId");

                    b.ToTable("PackageProduct", "DontWasteFood");

                    b.HasData(
                        new
                        {
                            PackagesId = new Guid("18f10e8e-95c0-40bd-81a6-79e98b01cc8f"),
                            ProductsId = new Guid("73209267-a1ed-45a3-8ea2-a97074f38232")
                        },
                        new
                        {
                            PackagesId = new Guid("18f10e8e-95c0-40bd-81a6-79e98b01cc8f"),
                            ProductsId = new Guid("44a61765-faa6-4112-9f27-31470b00e70c")
                        },
                        new
                        {
                            PackagesId = new Guid("f22e219d-cdeb-4292-b09c-a03228b6fb27"),
                            ProductsId = new Guid("db7b1a0e-6920-4bd2-b517-dc411635f85e")
                        },
                        new
                        {
                            PackagesId = new Guid("f22e219d-cdeb-4292-b09c-a03228b6fb27"),
                            ProductsId = new Guid("5d1c9a4e-7968-4f94-a81c-ecca866c73a1")
                        },
                        new
                        {
                            PackagesId = new Guid("46c3bc0c-1725-4d4b-8671-18fade721fac"),
                            ProductsId = new Guid("afbd7019-aba7-4d6f-adc5-3bc30960d161")
                        },
                        new
                        {
                            PackagesId = new Guid("68255d0d-fc3d-4e08-9b65-1b6d66a462fc"),
                            ProductsId = new Guid("157f4ced-fbed-403a-9efa-4e4a9b93257c")
                        },
                        new
                        {
                            PackagesId = new Guid("30bb508b-4b34-4176-9577-5ba9aeb94a6e"),
                            ProductsId = new Guid("3ae01902-607f-42d2-8748-7adbbc8b1b39")
                        },
                        new
                        {
                            PackagesId = new Guid("2444f203-d6e2-4ebe-a8cd-7ad0467a7164"),
                            ProductsId = new Guid("a0e1ffc4-39b9-4f3c-a242-a44172172229")
                        });
                });

            modelBuilder.Entity("DontWasteFood.Domain.Models.CanteenWorker", b =>
                {
                    b.HasOne("DontWasteFood.Domain.Models.Canteen", "Canteen")
                        .WithMany("CanteenWorkers")
                        .HasForeignKey("CanteenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Canteen");
                });

            modelBuilder.Entity("DontWasteFood.Domain.Models.Package", b =>
                {
                    b.HasOne("DontWasteFood.Domain.Models.Canteen", "Canteen")
                        .WithMany()
                        .HasForeignKey("CanteenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DontWasteFood.Domain.Models.Student", "ReservedBy")
                        .WithMany("Packages")
                        .HasForeignKey("StudentId");

                    b.Navigation("Canteen");

                    b.Navigation("ReservedBy");
                });

            modelBuilder.Entity("PackageProduct", b =>
                {
                    b.HasOne("DontWasteFood.Domain.Models.Package", null)
                        .WithMany()
                        .HasForeignKey("PackagesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DontWasteFood.Domain.Models.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DontWasteFood.Domain.Models.Canteen", b =>
                {
                    b.Navigation("CanteenWorkers");
                });

            modelBuilder.Entity("DontWasteFood.Domain.Models.Student", b =>
                {
                    b.Navigation("Packages");
                });
#pragma warning restore 612, 618
        }
    }
}
