// <auto-generated />
using System;
using DontWasteFood.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DontWasteFood.Infrastructure.Migrations.DontWasteFoodDb
{
    [DbContext(typeof(DontWasteFoodDbContext))]
    [Migration("20250110144708_AddedClaims")]
    partial class AddedClaims
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("DontWasteFood")
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DontWasteFood.Domain.Models.Canteen", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CanteenLocation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("City")
                        .HasColumnType("int");

                    b.Property<bool>("HotMealsOffer")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Canteens", "DontWasteFood");

                    b.HasData(
                        new
                        {
                            Id = new Guid("2977227e-fc29-4c85-b47b-f9149e276106"),
                            CanteenLocation = "LA",
                            City = 0,
                            HotMealsOffer = true
                        },
                        new
                        {
                            Id = new Guid("6dc1904c-4aa3-4967-852e-a97dee252d4f"),
                            CanteenLocation = "DB",
                            City = 1,
                            HotMealsOffer = true
                        });
                });

            modelBuilder.Entity("DontWasteFood.Domain.Models.CanteenWorker", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CanteenId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EmployeeNumber")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<string>("IdentityUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CanteenId");

                    b.HasIndex("EmployeeNumber")
                        .IsUnique();

                    b.ToTable("CanteenWorkers", "DontWasteFood");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4fdd4c4d-9cf0-4bfc-b9e4-df0329b7d77f"),
                            CanteenId = new Guid("2977227e-fc29-4c85-b47b-f9149e276106"),
                            EmployeeNumber = "1234567",
                            IdentityUserId = "4fdd4c4d-9cf0-4bfc-b9e4-df0329b7d77f",
                            Name = "John Doe"
                        },
                        new
                        {
                            Id = new Guid("3f6c83f1-608a-4e64-a458-80751865d4e3"),
                            CanteenId = new Guid("2977227e-fc29-4c85-b47b-f9149e276106"),
                            EmployeeNumber = "7654321",
                            Name = "Jan Jansen"
                        });
                });

            modelBuilder.Entity("DontWasteFood.Domain.Models.Package", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CanteenId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateOfPickUp")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Is18Plus")
                        .HasColumnType("bit");

                    b.Property<int>("MealType")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("StudentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("TimeOfPickUp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CanteenId");

                    b.HasIndex("StudentId");

                    b.ToTable("Packages", "DontWasteFood");

                    b.HasData(
                        new
                        {
                            Id = new Guid("57749a10-0541-4454-8daa-437fa6a96f0e"),
                            CanteenId = new Guid("2977227e-fc29-4c85-b47b-f9149e276106"),
                            DateOfPickUp = new DateTime(2024, 12, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Is18Plus = false,
                            MealType = 3,
                            Name = "Gevulde Koek met Fristi",
                            Price = 5.00m,
                            StudentId = new Guid("a96fda13-9eee-4a49-94b7-ddf4c84ec61e"),
                            TimeOfPickUp = new DateTime(2024, 12, 30, 16, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("598dae15-fe43-4762-980b-4715ab5d0232"),
                            CanteenId = new Guid("2977227e-fc29-4c85-b47b-f9149e276106"),
                            DateOfPickUp = new DateTime(2024, 12, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Is18Plus = true,
                            MealType = 2,
                            Name = "Amstel & Stroopwafel",
                            Price = 10.00m,
                            TimeOfPickUp = new DateTime(2024, 12, 13, 13, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("72ddfbb8-8dbc-4c45-a27e-ab4d62528535"),
                            CanteenId = new Guid("6dc1904c-4aa3-4967-852e-a97dee252d4f"),
                            DateOfPickUp = new DateTime(2024, 12, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Is18Plus = false,
                            MealType = 0,
                            Name = "Broodje Gezond",
                            Price = 3.00m,
                            TimeOfPickUp = new DateTime(2024, 12, 14, 11, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("bbea0c4e-6ba4-4a51-a1ea-bf47692fe611"),
                            CanteenId = new Guid("6dc1904c-4aa3-4967-852e-a97dee252d4f"),
                            DateOfPickUp = new DateTime(2024, 12, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Is18Plus = false,
                            MealType = 0,
                            Name = "Panini Salami",
                            Price = 4.00m,
                            TimeOfPickUp = new DateTime(2024, 12, 20, 15, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("DontWasteFood.Domain.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsAlcoholic")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products", "DontWasteFood");

                    b.HasData(
                        new
                        {
                            Id = new Guid("30ffa4a0-b826-4acf-b712-703722cc7fe5"),
                            IsAlcoholic = true,
                            Name = "Amstel",
                            PhotoUrl = "/images/amstel.jpg"
                        },
                        new
                        {
                            Id = new Guid("01ee85d2-6a88-426d-9b0f-8f325b2d6b70"),
                            IsAlcoholic = false,
                            Name = "Broodje gezond",
                            PhotoUrl = "/images/broodje-gezond.jpg"
                        },
                        new
                        {
                            Id = new Guid("8b1485f0-be0b-4f67-8e32-f077c50076bd"),
                            IsAlcoholic = false,
                            Name = "Cola",
                            PhotoUrl = "/images/cola.jpg"
                        },
                        new
                        {
                            Id = new Guid("d6813c93-f9d1-49e9-b1bb-8a64e02e80ac"),
                            IsAlcoholic = false,
                            Name = "Fanta",
                            PhotoUrl = "/images/fanta.png"
                        },
                        new
                        {
                            Id = new Guid("96a98c5a-01f8-4a84-b49b-adc3e4c9dba7"),
                            IsAlcoholic = false,
                            Name = "Fristi",
                            PhotoUrl = "/images/fristi.png"
                        },
                        new
                        {
                            Id = new Guid("6be992e3-511a-4c2e-9bd3-18a710475bc9"),
                            IsAlcoholic = false,
                            Name = "Gevulde Koek",
                            PhotoUrl = "/images/gevulde-koek.jpg"
                        },
                        new
                        {
                            Id = new Guid("feca07bd-9f2f-42d7-be80-ee5a68dcb3a8"),
                            IsAlcoholic = false,
                            Name = "Panini Salami",
                            PhotoUrl = "/images/panini-salami.jpg"
                        },
                        new
                        {
                            Id = new Guid("d3e34475-b352-40db-9124-0d7df352fb34"),
                            IsAlcoholic = false,
                            Name = "Saucijzenbroodje",
                            PhotoUrl = "/images/saucijzenbroodje.png"
                        },
                        new
                        {
                            Id = new Guid("4e37a893-d204-4585-b387-d60d54719d27"),
                            IsAlcoholic = false,
                            Name = "Spa Blauw",
                            PhotoUrl = "/images/spa-blauw.jpg"
                        },
                        new
                        {
                            Id = new Guid("fca1f141-9743-44ac-8a93-1c5aaa51b8c4"),
                            IsAlcoholic = false,
                            Name = "Stroopwafel",
                            PhotoUrl = "/images/stroopwafel.jpg"
                        });
                });

            modelBuilder.Entity("DontWasteFood.Domain.Models.Student", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("City")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("IdentityUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudentNumber")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.HasKey("Id");

                    b.HasIndex("EmailAddress")
                        .IsUnique();

                    b.HasIndex("StudentNumber")
                        .IsUnique();

                    b.ToTable("Students", "DontWasteFood");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a96fda13-9eee-4a49-94b7-ddf4c84ec61e"),
                            City = 0,
                            DateOfBirth = new DateTime(2004, 8, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "el.stam@student.avans.nl",
                            IdentityUserId = "a96fda13-9eee-4a49-94b7-ddf4c84ec61e",
                            Name = "Esmée Stam",
                            StudentNumber = "2196911"
                        },
                        new
                        {
                            Id = new Guid("e871695d-924c-4f81-bae3-d81b0a3e9362"),
                            City = 1,
                            DateOfBirth = new DateTime(2008, 3, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "j.doe@student.avans.nl",
                            Name = "Jane Doe",
                            StudentNumber = "2176034"
                        });
                });

            modelBuilder.Entity("PackageProduct", b =>
                {
                    b.Property<Guid>("PackagesId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductsId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PackagesId", "ProductsId");

                    b.HasIndex("ProductsId");

                    b.ToTable("PackageProduct", "DontWasteFood");

                    b.HasData(
                        new
                        {
                            PackagesId = new Guid("57749a10-0541-4454-8daa-437fa6a96f0e"),
                            ProductsId = new Guid("6be992e3-511a-4c2e-9bd3-18a710475bc9")
                        },
                        new
                        {
                            PackagesId = new Guid("57749a10-0541-4454-8daa-437fa6a96f0e"),
                            ProductsId = new Guid("96a98c5a-01f8-4a84-b49b-adc3e4c9dba7")
                        },
                        new
                        {
                            PackagesId = new Guid("598dae15-fe43-4762-980b-4715ab5d0232"),
                            ProductsId = new Guid("30ffa4a0-b826-4acf-b712-703722cc7fe5")
                        },
                        new
                        {
                            PackagesId = new Guid("598dae15-fe43-4762-980b-4715ab5d0232"),
                            ProductsId = new Guid("fca1f141-9743-44ac-8a93-1c5aaa51b8c4")
                        },
                        new
                        {
                            PackagesId = new Guid("72ddfbb8-8dbc-4c45-a27e-ab4d62528535"),
                            ProductsId = new Guid("01ee85d2-6a88-426d-9b0f-8f325b2d6b70")
                        },
                        new
                        {
                            PackagesId = new Guid("bbea0c4e-6ba4-4a51-a1ea-bf47692fe611"),
                            ProductsId = new Guid("feca07bd-9f2f-42d7-be80-ee5a68dcb3a8")
                        });
                });

            modelBuilder.Entity("DontWasteFood.Domain.Models.CanteenWorker", b =>
                {
                    b.HasOne("DontWasteFood.Domain.Models.Canteen", "Canteen")
                        .WithMany("CanteenWorkers")
                        .HasForeignKey("CanteenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Canteen");
                });

            modelBuilder.Entity("DontWasteFood.Domain.Models.Package", b =>
                {
                    b.HasOne("DontWasteFood.Domain.Models.Canteen", "Canteen")
                        .WithMany()
                        .HasForeignKey("CanteenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DontWasteFood.Domain.Models.Student", "ReservedBy")
                        .WithMany("Packages")
                        .HasForeignKey("StudentId");

                    b.Navigation("Canteen");

                    b.Navigation("ReservedBy");
                });

            modelBuilder.Entity("PackageProduct", b =>
                {
                    b.HasOne("DontWasteFood.Domain.Models.Package", null)
                        .WithMany()
                        .HasForeignKey("PackagesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DontWasteFood.Domain.Models.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DontWasteFood.Domain.Models.Canteen", b =>
                {
                    b.Navigation("CanteenWorkers");
                });

            modelBuilder.Entity("DontWasteFood.Domain.Models.Student", b =>
                {
                    b.Navigation("Packages");
                });
#pragma warning restore 612, 618
        }
    }
}
