// <auto-generated />
using System;
using DontWasteFood.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DontWasteFood.Infrastructure.Migrations.DontWasteFoodDb
{
    [DbContext(typeof(DontWasteFoodDbContext))]
    partial class DontWasteFoodDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("DontWasteFood")
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DontWasteFood.Domain.Models.Canteen", b =>
                {
                    b.Property<Guid>("CanteenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CanteenLocation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HotMealsOffer")
                        .HasColumnType("bit");

                    b.HasKey("CanteenId");

                    b.ToTable("Canteens", "DontWasteFood");

                    b.HasData(
                        new
                        {
                            CanteenId = new Guid("012fde28-9566-482c-ae9b-d5fc7d4ffe32"),
                            CanteenLocation = "LA",
                            City = "Breda",
                            HotMealsOffer = true
                        },
                        new
                        {
                            CanteenId = new Guid("c155bce0-27ad-4e9d-b96c-79269b49dbd1"),
                            CanteenLocation = "DB",
                            City = "Den Bosch",
                            HotMealsOffer = true
                        });
                });

            modelBuilder.Entity("DontWasteFood.Domain.Models.CanteenWorker", b =>
                {
                    b.Property<Guid>("CanteenWorkerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CanteenId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EmployeeNumber")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<string>("IdentityUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CanteenWorkerId");

                    b.HasIndex("CanteenId");

                    b.HasIndex("EmployeeNumber")
                        .IsUnique();

                    b.ToTable("CanteenWorkers", "DontWasteFood");

                    b.HasData(
                        new
                        {
                            CanteenWorkerId = new Guid("4fdd4c4d-9cf0-4bfc-b9e4-df0329b7d77f"),
                            CanteenId = new Guid("012fde28-9566-482c-ae9b-d5fc7d4ffe32"),
                            EmployeeNumber = "1234567",
                            IdentityUserId = "4fdd4c4d-9cf0-4bfc-b9e4-df0329b7d77f",
                            Name = "John Doe"
                        },
                        new
                        {
                            CanteenWorkerId = new Guid("64178fba-d17d-465a-990d-e5dfb9cf8b18"),
                            CanteenId = new Guid("012fde28-9566-482c-ae9b-d5fc7d4ffe32"),
                            EmployeeNumber = "7654321",
                            Name = "Jan Jansen"
                        });
                });

            modelBuilder.Entity("DontWasteFood.Domain.Models.Package", b =>
                {
                    b.Property<Guid>("PackageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CanteenId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateOfPickUp")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Is18Plus")
                        .HasColumnType("bit");

                    b.Property<int>("MealType")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("StudentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("TimeOfPickUp")
                        .HasColumnType("datetime2");

                    b.HasKey("PackageId");

                    b.HasIndex("CanteenId");

                    b.HasIndex("StudentId");

                    b.ToTable("Packages", "DontWasteFood");

                    b.HasData(
                        new
                        {
                            PackageId = new Guid("3cb1b9ec-f3d0-4f53-bdcf-01d7804a7f80"),
                            CanteenId = new Guid("012fde28-9566-482c-ae9b-d5fc7d4ffe32"),
                            DateOfPickUp = new DateTime(2024, 12, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Is18Plus = false,
                            MealType = 3,
                            Name = "Gevulde Koek met Fristi",
                            Price = 5.00m,
                            StudentId = new Guid("a96fda13-9eee-4a49-94b7-ddf4c84ec61e"),
                            TimeOfPickUp = new DateTime(2024, 12, 30, 16, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PackageId = new Guid("30bbebe7-938e-4aa2-9b4a-cd3716bc593f"),
                            CanteenId = new Guid("012fde28-9566-482c-ae9b-d5fc7d4ffe32"),
                            DateOfPickUp = new DateTime(2024, 12, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Is18Plus = true,
                            MealType = 2,
                            Name = "Amstel & Stroopwafel",
                            Price = 10.00m,
                            TimeOfPickUp = new DateTime(2024, 12, 13, 13, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PackageId = new Guid("0ed5e837-e5c6-44e9-96fd-566076b95f9c"),
                            CanteenId = new Guid("c155bce0-27ad-4e9d-b96c-79269b49dbd1"),
                            DateOfPickUp = new DateTime(2024, 12, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Is18Plus = false,
                            MealType = 0,
                            Name = "Broodje Gezond",
                            Price = 3.00m,
                            TimeOfPickUp = new DateTime(2024, 12, 14, 11, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PackageId = new Guid("51bc1c46-b45e-4e3a-889a-f13de34eed1c"),
                            CanteenId = new Guid("c155bce0-27ad-4e9d-b96c-79269b49dbd1"),
                            DateOfPickUp = new DateTime(2024, 12, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Is18Plus = false,
                            MealType = 0,
                            Name = "Panini Salami",
                            Price = 4.00m,
                            TimeOfPickUp = new DateTime(2024, 12, 20, 15, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("DontWasteFood.Domain.Models.Product", b =>
                {
                    b.Property<Guid>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsAlcoholic")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductId");

                    b.ToTable("Products", "DontWasteFood");

                    b.HasData(
                        new
                        {
                            ProductId = new Guid("55fd481a-0a22-4495-8904-465e89304439"),
                            IsAlcoholic = true,
                            Name = "Amstel",
                            PhotoUrl = "/images/amstel.jpg"
                        },
                        new
                        {
                            ProductId = new Guid("950577a0-2b52-4550-94bf-e2a9e375b415"),
                            IsAlcoholic = false,
                            Name = "Broodje gezond",
                            PhotoUrl = "/images/broodje-gezond.jpg"
                        },
                        new
                        {
                            ProductId = new Guid("33afbc2b-027b-4359-bcc3-13aebd0f92c3"),
                            IsAlcoholic = true,
                            Name = "Cola",
                            PhotoUrl = "/images/cola.jpg"
                        },
                        new
                        {
                            ProductId = new Guid("fc4ff700-6129-4f47-ace7-62022c7697fa"),
                            IsAlcoholic = false,
                            Name = "Fanta",
                            PhotoUrl = "/images/fanta.png"
                        },
                        new
                        {
                            ProductId = new Guid("9f27fb92-d4ff-4992-a958-4896fb9ba4f9"),
                            IsAlcoholic = false,
                            Name = "Fristi",
                            PhotoUrl = "/images/fristi.png"
                        },
                        new
                        {
                            ProductId = new Guid("fb4c0a43-3bba-4169-8457-17a0cd8f5cd0"),
                            IsAlcoholic = false,
                            Name = "Gevulde Koek",
                            PhotoUrl = "/images/gevulde-koek.jpg"
                        },
                        new
                        {
                            ProductId = new Guid("412640a7-4fc7-4f42-be43-bd6ddbce6390"),
                            IsAlcoholic = false,
                            Name = "Panini Salami",
                            PhotoUrl = "/images/panini-salami.jpg"
                        },
                        new
                        {
                            ProductId = new Guid("87ba0997-4a1c-48a6-b799-9e89bdd054fa"),
                            IsAlcoholic = false,
                            Name = "Saucijzenbroodje",
                            PhotoUrl = "/images/saucijzenbroodje.png"
                        },
                        new
                        {
                            ProductId = new Guid("706044eb-31ab-4a78-960b-490bb7a1bb14"),
                            IsAlcoholic = false,
                            Name = "Spa Blauw",
                            PhotoUrl = "/images/spa-blauw.jpg"
                        },
                        new
                        {
                            ProductId = new Guid("f8c64b40-26b9-4f1b-88a7-50579f4ae4e9"),
                            IsAlcoholic = false,
                            Name = "Stroopwafel",
                            PhotoUrl = "/images/stroopwafel.jpg"
                        });
                });

            modelBuilder.Entity("DontWasteFood.Domain.Models.Student", b =>
                {
                    b.Property<Guid>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("IdentityUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudentNumber")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.HasKey("StudentId");

                    b.HasIndex("EmailAddress")
                        .IsUnique();

                    b.HasIndex("StudentNumber")
                        .IsUnique();

                    b.ToTable("Students", "DontWasteFood");

                    b.HasData(
                        new
                        {
                            StudentId = new Guid("a96fda13-9eee-4a49-94b7-ddf4c84ec61e"),
                            City = "Breda",
                            DateOfBirth = new DateTime(2004, 8, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "el.stam@student.avans.nl",
                            IdentityUserId = "a96fda13-9eee-4a49-94b7-ddf4c84ec61e",
                            Name = "Esmée Stam",
                            StudentNumber = "2196911"
                        },
                        new
                        {
                            StudentId = new Guid("79cc8327-56e7-474b-936f-11717168a98b"),
                            City = "Den Bosch",
                            DateOfBirth = new DateTime(2008, 3, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "j.doe@student.avans.nl",
                            Name = "Jane Doe",
                            StudentNumber = "2176034"
                        });
                });

            modelBuilder.Entity("PackageProduct", b =>
                {
                    b.Property<Guid>("PackagesPackageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductsProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PackageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PackagesPackageId", "ProductsProductId");

                    b.HasIndex("PackageId");

                    b.HasIndex("ProductId");

                    b.HasIndex("ProductsProductId");

                    b.ToTable("PackageProduct", "DontWasteFood");

                    b.HasData(
                        new
                        {
                            PackagesPackageId = new Guid("3cb1b9ec-f3d0-4f53-bdcf-01d7804a7f80"),
                            ProductsProductId = new Guid("fb4c0a43-3bba-4169-8457-17a0cd8f5cd0")
                        },
                        new
                        {
                            PackagesPackageId = new Guid("3cb1b9ec-f3d0-4f53-bdcf-01d7804a7f80"),
                            ProductsProductId = new Guid("9f27fb92-d4ff-4992-a958-4896fb9ba4f9")
                        },
                        new
                        {
                            PackagesPackageId = new Guid("30bbebe7-938e-4aa2-9b4a-cd3716bc593f"),
                            ProductsProductId = new Guid("55fd481a-0a22-4495-8904-465e89304439")
                        },
                        new
                        {
                            PackagesPackageId = new Guid("30bbebe7-938e-4aa2-9b4a-cd3716bc593f"),
                            ProductsProductId = new Guid("f8c64b40-26b9-4f1b-88a7-50579f4ae4e9")
                        },
                        new
                        {
                            PackagesPackageId = new Guid("0ed5e837-e5c6-44e9-96fd-566076b95f9c"),
                            ProductsProductId = new Guid("950577a0-2b52-4550-94bf-e2a9e375b415")
                        },
                        new
                        {
                            PackagesPackageId = new Guid("51bc1c46-b45e-4e3a-889a-f13de34eed1c"),
                            ProductsProductId = new Guid("412640a7-4fc7-4f42-be43-bd6ddbce6390")
                        });
                });

            modelBuilder.Entity("DontWasteFood.Domain.Models.CanteenWorker", b =>
                {
                    b.HasOne("DontWasteFood.Domain.Models.Canteen", "Canteen")
                        .WithMany("CanteenWorkers")
                        .HasForeignKey("CanteenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Canteen");
                });

            modelBuilder.Entity("DontWasteFood.Domain.Models.Package", b =>
                {
                    b.HasOne("DontWasteFood.Domain.Models.Canteen", "Canteen")
                        .WithMany()
                        .HasForeignKey("CanteenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DontWasteFood.Domain.Models.Student", "ReservedBy")
                        .WithMany("Packages")
                        .HasForeignKey("StudentId");

                    b.Navigation("Canteen");

                    b.Navigation("ReservedBy");
                });

            modelBuilder.Entity("PackageProduct", b =>
                {
                    b.HasOne("DontWasteFood.Domain.Models.Package", null)
                        .WithMany()
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DontWasteFood.Domain.Models.Package", null)
                        .WithMany()
                        .HasForeignKey("PackagesPackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DontWasteFood.Domain.Models.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DontWasteFood.Domain.Models.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductsProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DontWasteFood.Domain.Models.Canteen", b =>
                {
                    b.Navigation("CanteenWorkers");
                });

            modelBuilder.Entity("DontWasteFood.Domain.Models.Student", b =>
                {
                    b.Navigation("Packages");
                });
#pragma warning restore 612, 618
        }
    }
}
