// <auto-generated />
using System;
using DontWasteFood.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DontWasteFood.Infrastructure.Migrations.DontWasteFoodDb
{
    [DbContext(typeof(DontWasteFoodDbContext))]
    partial class DontWasteFoodDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("DontWasteFood")
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DontWasteFood.Domain.Models.Canteen", b =>
                {
                    b.Property<Guid>("CanteenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CanteenLocation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HotMealsOffer")
                        .HasColumnType("bit");

                    b.HasKey("CanteenId");

                    b.ToTable("Canteens", "DontWasteFood");

                    b.HasData(
                        new
                        {
                            CanteenId = new Guid("f2b032c4-6ae9-4d93-a113-39739aa7798f"),
                            CanteenLocation = "LA",
                            City = "Breda",
                            HotMealsOffer = true
                        },
                        new
                        {
                            CanteenId = new Guid("8436378f-7334-408e-901c-c0d69e1a9cbb"),
                            CanteenLocation = "DB",
                            City = "Den_Bosch",
                            HotMealsOffer = true
                        });
                });

            modelBuilder.Entity("DontWasteFood.Domain.Models.CanteenWorker", b =>
                {
                    b.Property<Guid>("CanteenWorkerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CanteenId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EmployeeNumber")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<string>("IdentityUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CanteenWorkerId");

                    b.HasIndex("CanteenId");

                    b.HasIndex("EmployeeNumber")
                        .IsUnique();

                    b.ToTable("CanteenWorkers", "DontWasteFood");

                    b.HasData(
                        new
                        {
                            CanteenWorkerId = new Guid("4fdd4c4d-9cf0-4bfc-b9e4-df0329b7d77f"),
                            CanteenId = new Guid("f2b032c4-6ae9-4d93-a113-39739aa7798f"),
                            EmployeeNumber = "1234567",
                            IdentityUserId = "4fdd4c4d-9cf0-4bfc-b9e4-df0329b7d77f",
                            Name = "John Doe"
                        },
                        new
                        {
                            CanteenWorkerId = new Guid("dde44693-b0aa-414b-a105-d631e9158887"),
                            CanteenId = new Guid("f2b032c4-6ae9-4d93-a113-39739aa7798f"),
                            EmployeeNumber = "7654321",
                            Name = "Jan Jansen"
                        });
                });

            modelBuilder.Entity("DontWasteFood.Domain.Models.Package", b =>
                {
                    b.Property<Guid>("PackageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CanteenId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateOfPickUp")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Is18Plus")
                        .HasColumnType("bit");

                    b.Property<string>("MealType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("StudentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("TimeOfPickUp")
                        .HasColumnType("datetime2");

                    b.HasKey("PackageId");

                    b.HasIndex("CanteenId");

                    b.HasIndex("StudentId");

                    b.ToTable("Packages", "DontWasteFood");

                    b.HasData(
                        new
                        {
                            PackageId = new Guid("13e6fa87-f2a0-41ee-8b82-c22380a438f8"),
                            CanteenId = new Guid("f2b032c4-6ae9-4d93-a113-39739aa7798f"),
                            DateOfPickUp = new DateTime(2024, 12, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Is18Plus = false,
                            MealType = "Anders",
                            Name = "Gevulde Koek met Fristi",
                            Price = 5.00m,
                            StudentId = new Guid("a96fda13-9eee-4a49-94b7-ddf4c84ec61e"),
                            TimeOfPickUp = new DateTime(2024, 12, 30, 16, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PackageId = new Guid("49901b45-ab3a-47ae-9835-d37fe6be9586"),
                            CanteenId = new Guid("f2b032c4-6ae9-4d93-a113-39739aa7798f"),
                            DateOfPickUp = new DateTime(2024, 12, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Is18Plus = true,
                            MealType = "Drank",
                            Name = "Amstel & Stroopwafel",
                            Price = 10.00m,
                            TimeOfPickUp = new DateTime(2024, 12, 13, 13, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PackageId = new Guid("a0cff8f0-7981-4219-a0b6-ce500019e5b0"),
                            CanteenId = new Guid("8436378f-7334-408e-901c-c0d69e1a9cbb"),
                            DateOfPickUp = new DateTime(2024, 12, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Is18Plus = false,
                            MealType = "Brood",
                            Name = "Broodje Gezond",
                            Price = 3.00m,
                            TimeOfPickUp = new DateTime(2024, 12, 14, 11, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PackageId = new Guid("b9e2eb0b-c9ba-4247-8168-82b6184eba9f"),
                            CanteenId = new Guid("8436378f-7334-408e-901c-c0d69e1a9cbb"),
                            DateOfPickUp = new DateTime(2024, 12, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Is18Plus = false,
                            MealType = "Brood",
                            Name = "Panini Salami",
                            Price = 4.00m,
                            TimeOfPickUp = new DateTime(2024, 12, 20, 15, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("DontWasteFood.Domain.Models.Product", b =>
                {
                    b.Property<Guid>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsAlcoholic")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductId");

                    b.ToTable("Products", "DontWasteFood");

                    b.HasData(
                        new
                        {
                            ProductId = new Guid("275df27f-c998-4870-bf08-9598d64cd766"),
                            IsAlcoholic = true,
                            Name = "Amstel",
                            PhotoUrl = "/images/amstel.jpg"
                        },
                        new
                        {
                            ProductId = new Guid("4a7eb8c7-887b-48d0-ad07-d1c0f1072c54"),
                            IsAlcoholic = false,
                            Name = "Broodje gezond",
                            PhotoUrl = "/images/broodje-gezond.jpg"
                        },
                        new
                        {
                            ProductId = new Guid("8ebceb33-1069-408b-99b4-70a85a441cfd"),
                            IsAlcoholic = true,
                            Name = "Cola",
                            PhotoUrl = "/images/cola.jpg"
                        },
                        new
                        {
                            ProductId = new Guid("26ce3003-177e-4479-812a-3140d88bdc0f"),
                            IsAlcoholic = false,
                            Name = "Fanta",
                            PhotoUrl = "/images/fanta.png"
                        },
                        new
                        {
                            ProductId = new Guid("135bb552-e394-422b-b848-6a29d6c52083"),
                            IsAlcoholic = false,
                            Name = "Fristi",
                            PhotoUrl = "/images/fristi.png"
                        },
                        new
                        {
                            ProductId = new Guid("0b3ec876-7240-4f40-9f0e-937148207b79"),
                            IsAlcoholic = false,
                            Name = "Gevulde Koek",
                            PhotoUrl = "/images/gevulde-koek.jpg"
                        },
                        new
                        {
                            ProductId = new Guid("e16463ba-b001-42ae-a667-03cfaf42c2b9"),
                            IsAlcoholic = false,
                            Name = "Panini Salami",
                            PhotoUrl = "/images/panini-salami.jpg"
                        },
                        new
                        {
                            ProductId = new Guid("6744b650-1663-49a8-be2a-713f58d23aaf"),
                            IsAlcoholic = false,
                            Name = "Saucijzenbroodje",
                            PhotoUrl = "/images/saucijzenbroodje.png"
                        },
                        new
                        {
                            ProductId = new Guid("1cb9eaa6-ad70-4c08-8fa1-32efb6c9e316"),
                            IsAlcoholic = false,
                            Name = "Spa Blauw",
                            PhotoUrl = "/images/spa-blauw.jpg"
                        },
                        new
                        {
                            ProductId = new Guid("ff977bf2-f1e8-4855-ab91-6dae52e940dc"),
                            IsAlcoholic = false,
                            Name = "Stroopwafel",
                            PhotoUrl = "/images/stroopwafel.jpg"
                        });
                });

            modelBuilder.Entity("DontWasteFood.Domain.Models.Student", b =>
                {
                    b.Property<Guid>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("IdentityUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudentNumber")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.HasKey("StudentId");

                    b.HasIndex("EmailAddress")
                        .IsUnique();

                    b.HasIndex("StudentNumber")
                        .IsUnique();

                    b.ToTable("Students", "DontWasteFood");

                    b.HasData(
                        new
                        {
                            StudentId = new Guid("a96fda13-9eee-4a49-94b7-ddf4c84ec61e"),
                            City = "Breda",
                            DateOfBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "el.stam@student.avans.nl",
                            IdentityUserId = "a96fda13-9eee-4a49-94b7-ddf4c84ec61e",
                            Name = "Esmée Stam",
                            StudentNumber = "2196911"
                        },
                        new
                        {
                            StudentId = new Guid("84ec1d54-3271-43cd-a710-b7bde131b404"),
                            City = "Den_Bosch",
                            DateOfBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "j.doe@student.avans.nl",
                            Name = "Jane Doe",
                            StudentNumber = "2176034"
                        });
                });

            modelBuilder.Entity("PackageProduct", b =>
                {
                    b.Property<Guid>("PackagesPackageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductsProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PackageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PackagesPackageId", "ProductsProductId");

                    b.HasIndex("PackageId");

                    b.HasIndex("ProductId");

                    b.HasIndex("ProductsProductId");

                    b.ToTable("PackageProduct", "DontWasteFood");

                    b.HasData(
                        new
                        {
                            PackagesPackageId = new Guid("13e6fa87-f2a0-41ee-8b82-c22380a438f8"),
                            ProductsProductId = new Guid("0b3ec876-7240-4f40-9f0e-937148207b79")
                        },
                        new
                        {
                            PackagesPackageId = new Guid("13e6fa87-f2a0-41ee-8b82-c22380a438f8"),
                            ProductsProductId = new Guid("135bb552-e394-422b-b848-6a29d6c52083")
                        },
                        new
                        {
                            PackagesPackageId = new Guid("49901b45-ab3a-47ae-9835-d37fe6be9586"),
                            ProductsProductId = new Guid("275df27f-c998-4870-bf08-9598d64cd766")
                        },
                        new
                        {
                            PackagesPackageId = new Guid("49901b45-ab3a-47ae-9835-d37fe6be9586"),
                            ProductsProductId = new Guid("ff977bf2-f1e8-4855-ab91-6dae52e940dc")
                        },
                        new
                        {
                            PackagesPackageId = new Guid("a0cff8f0-7981-4219-a0b6-ce500019e5b0"),
                            ProductsProductId = new Guid("4a7eb8c7-887b-48d0-ad07-d1c0f1072c54")
                        },
                        new
                        {
                            PackagesPackageId = new Guid("b9e2eb0b-c9ba-4247-8168-82b6184eba9f"),
                            ProductsProductId = new Guid("e16463ba-b001-42ae-a667-03cfaf42c2b9")
                        });
                });

            modelBuilder.Entity("DontWasteFood.Domain.Models.CanteenWorker", b =>
                {
                    b.HasOne("DontWasteFood.Domain.Models.Canteen", "Canteen")
                        .WithMany("CanteenWorkers")
                        .HasForeignKey("CanteenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Canteen");
                });

            modelBuilder.Entity("DontWasteFood.Domain.Models.Package", b =>
                {
                    b.HasOne("DontWasteFood.Domain.Models.Canteen", "Canteen")
                        .WithMany()
                        .HasForeignKey("CanteenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DontWasteFood.Domain.Models.Student", "ReservedBy")
                        .WithMany("Packages")
                        .HasForeignKey("StudentId");

                    b.Navigation("Canteen");

                    b.Navigation("ReservedBy");
                });

            modelBuilder.Entity("PackageProduct", b =>
                {
                    b.HasOne("DontWasteFood.Domain.Models.Package", null)
                        .WithMany()
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DontWasteFood.Domain.Models.Package", null)
                        .WithMany()
                        .HasForeignKey("PackagesPackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DontWasteFood.Domain.Models.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DontWasteFood.Domain.Models.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductsProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DontWasteFood.Domain.Models.Canteen", b =>
                {
                    b.Navigation("CanteenWorkers");
                });

            modelBuilder.Entity("DontWasteFood.Domain.Models.Student", b =>
                {
                    b.Navigation("Packages");
                });
#pragma warning restore 612, 618
        }
    }
}
