// <auto-generated />
using System;
using DontWasteFood.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DontWasteFood.Infrastructure.Migrations
{
    [DbContext(typeof(AuthDbContext))]
    [Migration("20250119184220_MoreSeedData")]
    partial class MoreSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Authentication")
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", "Authentication");

                    b.HasData(
                        new
                        {
                            Id = "f61d531c-ea40-486f-bd97-5b3ac69fe033",
                            Name = "CanteenWorker",
                            NormalizedName = "CANTEENWORKER"
                        },
                        new
                        {
                            Id = "d13973e8-63e4-40d2-a939-c941eef836b4",
                            Name = "Student",
                            NormalizedName = "STUDENT"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", "Authentication");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", "Authentication");

                    b.HasData(
                        new
                        {
                            Id = "4fdd4c4d-9cf0-4bfc-b9e4-df0329b7d77f",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "2fea7054-73c6-4c14-85b6-a40f467f4bc5",
                            Email = "j.doe@avans.nl",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "J.DOE@AVANS.NL",
                            NormalizedUserName = "J.DOE@AVANS.NL",
                            PasswordHash = "AQAAAAIAAYagAAAAEF7NtnkMQpIlSQ9RWgQIkFbUkMAdiMe4JXEy1n+60ek1+I7bwbqTtJjwfkgYJiRrWA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "07ecc12c-54df-4551-a0f8-42e4cdcd06b2",
                            TwoFactorEnabled = false,
                            UserName = "j.doe@avans.nl"
                        },
                        new
                        {
                            Id = "b1c79773-6d4c-4605-9603-1cf695f0cda3",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "48b0b260-d874-489e-8c12-d17768feee38",
                            Email = "t.timmermans@avans.nl",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "T.TIMMERMANS@AVANS>NL",
                            NormalizedUserName = "T.TIMMERMANS@AVANS.NL",
                            PasswordHash = "AQAAAAIAAYagAAAAEMBDVHBLQuOUiugSfL6IipUTxt/08R6FTgL4T6V1ac8HyZw5CMiDHwrT5l42Ly+9Nw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "ab9cc05c-4488-4f8d-aef4-edaa02952bc5",
                            TwoFactorEnabled = false,
                            UserName = "t.timmermans@avans.nl"
                        },
                        new
                        {
                            Id = "c49a1c5f-b9ad-49e9-8cb7-7fcb54b3b39a",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "cb975c0b-dbdf-4499-8b4b-08c08001f82d",
                            Email = "jh.jansen@avans.nl",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "JH.JANSEN@AVANS.NL",
                            NormalizedUserName = "JH.JANSEN@AVANS.NL",
                            PasswordHash = "AQAAAAIAAYagAAAAEJhOj1rO+Jr0GvjpsbkKN7eCz2uNAFPlTd2Cf/EHLSwhEI63P8GhTmzZn5a7Q6MarA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "7476f17d-b5fc-447d-96f8-a04a2ccb014a",
                            TwoFactorEnabled = false,
                            UserName = "jh.jansen@avans.nl"
                        },
                        new
                        {
                            Id = "1dbd6d2b-4efb-4b56-93bc-90799c9beea5",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "fd8dc596-d2b7-4858-b66c-281fa3288aae",
                            Email = "j.jansen@avans.nl",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "J.JANSEN@AVANS>NL",
                            NormalizedUserName = "J.JANSEN@AVANS.NL",
                            PasswordHash = "AQAAAAIAAYagAAAAEFDSvLyueTsazwgi6ZEKrcNsGIHKt1SbZucOxv9lNYV+LiQPFbqOOLKjd2fJIwYQ2w==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "e1d68df3-a4eb-4784-abb7-fa7f64630c3a",
                            TwoFactorEnabled = false,
                            UserName = "j.jansen@avans.nl"
                        },
                        new
                        {
                            Id = "a96fda13-9eee-4a49-94b7-ddf4c84ec61e",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "6dc2253f-7b55-4b44-a291-b58bb199395e",
                            Email = "el.stam@student.avans.nl",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "EL.STAM@STUDENT.AVANS.NL",
                            NormalizedUserName = "EL.STAM@STUDENT.AVANS.NL",
                            PasswordHash = "AQAAAAIAAYagAAAAELnQdSYcZlIFvJ4Hj3XJeGmvPnZrC4/hlp452qF2qmjwEygS6OYC3S4RS1/vPd0vDw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "2d9d8637-3699-46e9-867f-9141119ee233",
                            TwoFactorEnabled = false,
                            UserName = "el.stam@student.avans.nl"
                        },
                        new
                        {
                            Id = "bbfe56c9-88c2-4a60-9479-18b16d8c4c9d",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "f04d84e0-c8cc-4f30-8384-39a80e9e2e2f",
                            Email = "j.doe@student.avans.nl",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "J.DOE@STUDENT.AVANS.NL",
                            NormalizedUserName = "J.DOE@STUDENT.AVANS.NL",
                            PasswordHash = "AQAAAAIAAYagAAAAEJ/Y/RWBhAizAxK78rZUSeryZ1oKQKCdxfj4rFN68ahqOsz/V+aMgJkD5MEH27+DIg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "a9735db9-2367-4573-bd62-61bf8128a64b",
                            TwoFactorEnabled = false,
                            UserName = "j.doe@student.avans.nl"
                        },
                        new
                        {
                            Id = "ea05a0b1-ea38-4c51-bde9-13c6fbb4b61b",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "e317eb47-66d8-4c57-a4b6-dc3ccdb4bb07",
                            Email = "n.jones@student.avans.nl",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "N.JONES@STUDENT.AVANS.NL",
                            NormalizedUserName = "N.JONES@STUDENT.AVANS.NL",
                            PasswordHash = "AQAAAAIAAYagAAAAEFjCLKfkdjk7L/JFCnkENxTW/e4nQ79uRUoBgE32LUSVOSf5nFGGbpfJOOkbxfGhOg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "295f2ed1-383c-4789-9049-207497d1b6cc",
                            TwoFactorEnabled = false,
                            UserName = "n.jones@student.avans.nl"
                        },
                        new
                        {
                            Id = "c16e4b0b-d7b3-4845-a788-52411e76b5de",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "a896c007-a678-4e5e-8e5e-7b8131574a84",
                            Email = "e.smith@student.avans.nl",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "E.SMITH@STUDENT.AVANS.NL",
                            NormalizedUserName = "E.SMITH@STUDENT.AVANS.NL",
                            PasswordHash = "AQAAAAIAAYagAAAAEG45WMiOpIOKdpypAOwkHTVW/AxHXV0eE1eqnEQR+wSoOeFnuA64JSNfju3dSEfrbQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "011f09bd-b17e-4457-bf73-c40ae5e792c2",
                            TwoFactorEnabled = false,
                            UserName = "e.smith@student.avans.nl"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", "Authentication");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClaimType = "http://schemas.microsoft.com/ws/2008/06/identity/claims/role",
                            ClaimValue = "CanteenWorker",
                            UserId = "4fdd4c4d-9cf0-4bfc-b9e4-df0329b7d77f"
                        },
                        new
                        {
                            Id = 3,
                            ClaimType = "http://schemas.microsoft.com/ws/2008/06/identity/claims/role",
                            ClaimValue = "CanteenWorker",
                            UserId = "b1c79773-6d4c-4605-9603-1cf695f0cda3"
                        },
                        new
                        {
                            Id = 4,
                            ClaimType = "http://schemas.microsoft.com/ws/2008/06/identity/claims/role",
                            ClaimValue = "CanteenWorker",
                            UserId = "c49a1c5f-b9ad-49e9-8cb7-7fcb54b3b39a"
                        },
                        new
                        {
                            Id = 5,
                            ClaimType = "http://schemas.microsoft.com/ws/2008/06/identity/claims/role",
                            ClaimValue = "CanteenWorker",
                            UserId = "1dbd6d2b-4efb-4b56-93bc-90799c9beea5"
                        },
                        new
                        {
                            Id = 2,
                            ClaimType = "http://schemas.microsoft.com/ws/2008/06/identity/claims/role",
                            ClaimValue = "Student",
                            UserId = "a96fda13-9eee-4a49-94b7-ddf4c84ec61e"
                        },
                        new
                        {
                            Id = 6,
                            ClaimType = "http://schemas.microsoft.com/ws/2008/06/identity/claims/role",
                            ClaimValue = "Student",
                            UserId = "bbfe56c9-88c2-4a60-9479-18b16d8c4c9d"
                        },
                        new
                        {
                            Id = 7,
                            ClaimType = "http://schemas.microsoft.com/ws/2008/06/identity/claims/role",
                            ClaimValue = "Student",
                            UserId = "ea05a0b1-ea38-4c51-bde9-13c6fbb4b61b"
                        },
                        new
                        {
                            Id = 8,
                            ClaimType = "http://schemas.microsoft.com/ws/2008/06/identity/claims/role",
                            ClaimValue = "Student",
                            UserId = "c16e4b0b-d7b3-4845-a788-52411e76b5de"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", "Authentication");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", "Authentication");

                    b.HasData(
                        new
                        {
                            UserId = "4fdd4c4d-9cf0-4bfc-b9e4-df0329b7d77f",
                            RoleId = "f61d531c-ea40-486f-bd97-5b3ac69fe033"
                        },
                        new
                        {
                            UserId = "a96fda13-9eee-4a49-94b7-ddf4c84ec61e",
                            RoleId = "d13973e8-63e4-40d2-a939-c941eef836b4"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", "Authentication");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
